require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Env = require("spec.support.zotero_env")
local FakeUI = require("spec.support.fake_ui")
local Browser = require("zoterobrowser")
local DocSettings = require("docsettings")

describe("Zotero local reading", function()
    local env, api, runtime, browser
    before_each(function()
        env = Env.new()
        api = env.api
        env:library()
        runtime = FakeUI.new()
        runtime.online = false
        browser = runtime:newBrowser(Browser, api)
    end)

    it("opens stale and unversioned copies without credentials, tasks or HTTP", function()
        for _, key in ipairs({ "ATTACH01", "ATTACH02" }) do
            local path = env:file(key, "original document", key == "ATTACH01" and 1 or nil)
            local sidecar = DocSettings:getSidecarDir(path)
            assert(api.util.mkdir(sidecar))
            assert.is_nil(api.util.write(sidecar .. "/metadata.lua", "reading position and annotations"))
            browser:onMenuSelect({ key = key, downloaded = false })
            assert.equals(path, runtime.opened_path)
            assert.equals("original document", api.util.read(path))
            assert.equals("reading position and annotations", api.util.read(sidecar .. "/metadata.lua"))
            assert.equals(key == "ATTACH01" and "1" or nil, api.util.read(api.getVersionPath(key)))
        end
        assert.equals(0, runtime.wraps)
        assert.equals(0, runtime.runner.calls)
        assert.equals(0, #runtime.shown)
        assert.equals(0, env.http:callCount())
    end)

    it("opens present linked files even while a network operation is queued", function()
        local path = env:file("LINKED01")
        api.beginOperation("sync")
        browser:onMenuSelect({ key = "LINKED01" })
        assert.equals(path, runtime.opened_path)
        assert.equals("sync", api.operation)
        assert.equals(0, runtime.wraps)
        assert.equals(0, env.http:callCount())
    end)

    it("rechecks file presence instead of trusting a previously downloaded row", function()
        local path = env:file("ATTACH01")
        local row = api.displayOnDevice()[1]
        assert(os.remove(path))
        browser:onMenuSelect(row)
        assert.is_nil(runtime.opened_path)
        assert.equals(1, runtime.runner.calls)
        assert.truthy(runtime:last().text:find("must set User ID", 1, true))
        assert.equals(0, env.http:callCount())
    end)

    it("keeps missing files on the normal download path with read-only requests", function()
        env:credentials()
        env.http:on("GET", "/items/ATTACH01/file", { body = "downloaded" })
        browser:onMenuSelect({ key = "ATTACH01" })
        assert.equals(api.getLocalAttachmentPath("ATTACH01"), runtime.opened_path)
        assert.equals(1, runtime.runner.calls)
        assert.equals(1, env.http:callCount())
        assert.equals("GET", env.http.calls[1].method)
    end)

    it("only resolves safe readable attachments and regular files", function()
        for _, key in ipairs({ "MISSING", "PARENT01", "NOTE0001", "EMBEDIMG", "ATTACH01" }) do
            assert.is_nil(api.getLocalAttachmentPath(key))
        end
        local directory, path = api.getDirAndPath("ATTACH01")
        assert(api.util.mkdir(path))
        assert.is_nil(api.getLocalAttachmentPath("ATTACH01"))
        assert.is_nil(api.util.write(directory .. "/outside.pdf", "existing"))
        for _, filename in ipairs({ "../outside.pdf", "/outside.pdf", "dir\\outside.pdf", ".." }) do
            api.getItems().ATTACH01.data.filename = filename
            assert.is_nil(api.getLocalAttachmentPath("ATTACH01"))
        end
    end)

    it("retains cache ownership and paths after removing the key and ID", function()
        env:credentials()
        api.setAccount("group", "99", "key")
        env:library()
        local path = env:file("ATTACH01")
        api.getSettings():delSetting("api_key")
        api.getSettings():delSetting("group_id")
        api.saveModifiedItems()
        api.init(env.root)
        assert.is_nil(api.getLibraryPrefix())
        assert.equals("groups/99", api.getLocalLibraryPrefix())
        browser:onMenuSelect({ key = "ATTACH01" })
        assert.equals(path, runtime.opened_path)
        assert.equals(0, env.http:callCount())
    end)

    it("lists current file presence without stale index flags or collection rows", function()
        env:attachment("ORPHAN", "MISSING", "orphan.pdf")
        local index = api.getIndex()
        assert.same({}, api.displayOnDevice())
        local path = env:file("ATTACH01", "stale", 1)
        env:file("LINKED01")
        env:file("ORPHAN")
        local rows = api.displayOnDevice()
        assert.equals(3, #rows)
        for _, row in ipairs(rows) do
            assert.is_true(row.downloaded)
            assert.is_nil(row.collection)
        end
        rows[1].title = "changed by UI"
        assert.is_not_equal("changed by UI", api.displayOnDevice()[1].title)
        assert(os.remove(path))
        assert.equals(2, #api.displayOnDevice())
        assert.equals(0, env.http:callCount())
        assert.equals(index, api.getIndex())
    end)

    it("limits On device searches and tags to local files in the active library", function()
        env:credentials()
        env:file("ATTACH01")
        env:file("STANDAL1")
        api.getItems().PARENT01.data.tags = { { tag = "Read" } }
        api.setItems(api.getItems())
        api.setFilterTag("Read")
        assert.equals(1, #api.displayOnDevice())
        assert.equals("ATTACH01", api.displayOnDevice("attention")[1].key)
        assert.equals(0, #api.displayOnDevice("standalone"))
        api.setAccount("group", "99", "key")
        env:library()
        api.setFilterTag("")
        assert.same({}, api.displayOnDevice())
    end)

    it("offers the local view at the root and keeps its search and empty state local", function()
        browser:displayHome()
        assert.equals("On device", browser.rows[4].text)
        browser:onMenuSelect(browser.rows[4])
        assert.equals("device", browser.current_view.kind)
        assert.is_true(browser.rows[1].is_label)
        browser:onMenuSelect(browser.rows[1])
        assert.equals(0, runtime.wraps)
        env:file("ATTACH01")
        browser:onLeftButtonTap()
        runtime:last().input = "attention"
        runtime:last().buttons[1][2].callback()
        assert.equals("device", browser.current_view.kind)
        assert.equals("ATTACH01", browser.rows[1].key)
        browser:onReturn()
        assert.equals("device", browser.current_view.kind)
        assert.equals("", browser.current_view.query)
        browser:onReturn()
        assert.equals("home", browser.current_view.kind)
    end)
end)
