require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Fixtures = require("spec.support.fixtures")
local EPUB = require("zoteroepub")
local Unicode = require("zoterounicode")
local XML = require("zoteroxml")
local CFI = require("zoterocfi")
local Registry = require("document/documentregistry")

describe("Zotero EPUB location conversion", function()
    local doc, codec
    before_each(function()
        doc = assert(Registry:openDocument(Fixtures.dir .. "positions/sample.epub"))
        doc:requestDomVersion(20260812); assert(doc:loadDocument()); doc:render()
        codec = EPUB.new(doc, 20260812)
    end)
    after_each(function() doc:close() end)

    it("converts the oracle corpus into exact live native passages", function()
        for _, point in ipairs(Fixtures.decode("positions/source.json").cases) do
            local cfi, err = codec:encode(point.pointer); assert.truthy(cfi, err)
            local decoded, reason = codec:decode(cfi); assert.truthy(decoded, reason)
            assert.equals(doc:getTextFromXPointer(point.pointer), doc:getTextFromXPointer(decoded))
            assert.equals(cfi, codec:encode(decoded))
        end
    end)
    it("uses source offsets when crengine collapses whitespace", function()
        local cfi = assert(codec:encode("/body/DocFragment[1]/body/p[3]/text().3"))
        assert.truthy(cfi:find(":4)", 1, true))
        assert.is_nil(codec:decode(cfi:gsub(":4%)", ":2)")))
    end)
    it("keeps content locators stable across font and pagination changes", function()
        local pointer = "/body/DocFragment[2]/body/p/text().20"
        local original = assert(codec:encode(pointer))
        doc:setFontSize(36); doc:render()
        assert.equals(original, codec:encode(pointer))
        assert.equals(original, codec:encode(assert(codec:decode(original))))
        doc:setFontSize(14); doc:render()
        assert.equals(original, codec:encode(pointer))
    end)
    it("rejects corrupt locators, missing sections and invalid UTF-16 boundaries", function()
        local cfi = assert(codec:encode("/body/DocFragment[1]/body/p[1]/text().8"))
        for _, value in ipairs({ "bad", cfi:gsub("!/", "!/@"), cfi:gsub(":9%)", ":7)"),
            cfi:gsub("/6/2!", "/6/200!"), cfi:gsub("/6/2!", "/6/2[wrong]!"),
            cfi:gsub(":9%)", ":9000)"), cfi:gsub(":9%)", ":9~1)") }) do
            assert.is_nil(codec:decode(value))
        end
        assert.is_nil(codec:encode("/body/DocFragment[99]/body/p/text().0"))
    end)
    it("supports element-start positions without inventing a text offset", function()
        local cfi = assert(codec:encode("/body/DocFragment[1]/body/p[1]"))
        assert.is_nil(cfi:find(":"))
        assert.truthy(codec:decode(cfi))
    end)
    it("accepts the bare CFI persisted by Zotero 10 synced settings", function()
        local point, reason = codec:decode("/6/2!/4/2/1:0")
        assert.truthy(point, reason)
        assert.equals("Alpha 😀 beta & gamma.", doc:getTextFromXPointer(point))
        assert.equals("epubcfi(/6/2!/4/2/1:0)", codec:encode(point))
    end)
    it("translates supplementary Unicode as two UTF-16 units", function()
        assert.equals(3, Unicode.offset("a😀b", 2))
        assert.equals(2, Unicode.offset("a😀b", 3, true))
        assert.has_error(function() Unicode.offset("a😀b", 2, true) end)
        assert.has_error(function() Unicode.boundaries("\255") end)
        assert.has_error(function() Unicode.boundaries("\192\128") end)
    end)
    it("preserves namespace and mixed-content parsing without evaluating declarations", function()
        local tree = XML.parse('<x:root xmlns:x="urn:test">a<x:b id="b"/>c</x:root>')
        local root = XML.find(tree, "root")
        assert.equals("urn:test", root.namespace); assert.equals(3, #root.children)
        assert.has_error(function() XML.parse('<!DOCTYPE x [<!ENTITY e SYSTEM "file:///tmp/no">]><x>&e;</x>') end)
        assert.has_error(function() XML.parse("<a><b></a>") end)
    end)
    it("rejects unsupported ranges without silently using an endpoint", function()
        assert.has_error(function() CFI.parse("epubcfi(/6/2!/4,/2/1:0,/2/1:3)") end)
    end)
    it("reports structural transformations that cannot be mapped safely", function()
        local unsafe = assert(Registry:openDocument(Fixtures.dir .. "positions/unsupported.epub"))
        unsafe:requestDomVersion(20260812); assert(unsafe:loadDocument()); unsafe:render()
        local unsupported = EPUB.new(unsafe, 20260812)
        local point, reason = unsupported:encode("/body/DocFragment[1]/body/p[1]/text().0")
        assert.is_nil(point); assert.truthy(reason:find("MathML"))
        point, reason = unsupported:encode("/body/DocFragment[2]/body/p[1]/text().0")
        assert.is_nil(point); assert.truthy(reason:find("object"))
        unsafe:close()
    end)
end)
