require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Env = require("spec.support.zotero_env")
local Runner = require("spec.support.fake_task_runner")
local Fixtures = require("spec.support.fixtures")

describe("Zotero offline collection downloads", function()
    local env, api
    before_each(function()
        env = Env.new()
        api = env.api
        env:credentials()
        env:library()
    end)

    it("downloads only direct members and reports count before each file", function()
        env.http:on("GET", "/items/STANDAL1/file", { body = "standalone" })
        env.http:on("GET", "/items/ATTACH01/file", { body = "paper" })
        local events = {}
        local result = api.downloadCollection("COLLAAA1", function(progress, entry)
            table.insert(events, { progress.total, progress.downloaded, entry.key })
        end)
        assert.same({ { 2, 0, "STANDAL1" }, { 2, 1, "ATTACH01" } }, events)
        assert.equals(2, result.downloaded)
        assert.equals(0, result.failed)
        assert.equals(2, env.http:callCount())
    end)

    it("skips current files without running a worker or using the network", function()
        env:file("ATTACH01", "paper", 1201)
        env:file("STANDAL1", "standalone", 1203)
        local runner = Runner.new()
        local result = api.downloadCollection("COLLAAA1", nil, function(task) return runner:run(task) end)
        assert.equals(2, result.skipped)
        assert.equals(0, result.downloaded)
        assert.equals(0, runner.calls)
        assert.equals(0, env.http:callCount())
    end)

    it("continues after a linked file and reports its specific failure", function()
        env.http:on("GET", "/items/ATTACH02/file", { body = "epub" })
        local result = api.downloadCollection("COLLCCC3")
        assert.equals(1, result.downloaded)
        assert.equals(1, result.failed)
        assert.equals("LINKED01", result.errors[1].key)
        assert.truthy(result.errors[1].text:find("linked attachment", 1, true))
    end)

    it("continues after a transport failure", function()
        env.http:on("GET", "/items/STANDAL1/file", { error = "offline" })
        env.http:on("GET", "/items/ATTACH01/file", { body = "paper" })
        local result = api.downloadCollection("COLLAAA1")
        assert.equals(1, result.downloaded)
        assert.equals(1, result.failed)
        assert.equals("STANDAL1", result.errors[1].key)
    end)

    it("uses the active tag filter without recursively including descendants", function()
        api.getItems().PARENT01.data.tags = { { tag = "Read" } }
        api.setFilterTag("Read")
        env.http:on("GET", "/items/ATTACH01/file", { body = "paper" })
        assert.equals(1, api.downloadCollection("COLLAAA1").downloaded)
        assert.equals(1, env.http:callCount())
    end)

    it("handles empty collections without calling the runner", function()
        local runner = Runner.new()
        local result = api.downloadCollection("COLLBBB2", nil, function(task) return runner:run(task) end)
        assert.equals(0, result.total)
        assert.equals(0, runner.calls)
    end)

    it("cancels between files and retains completed downloads", function()
        env.http:on("GET", "/items/STANDAL1/file", { body = "standalone" })
        local result = api.downloadCollection("COLLAAA1", function(progress)
            return progress.downloaded == 0
        end)
        assert.equals(1, result.downloaded)
        assert.equals(1, result.cancelled)
        assert.is_true(api.isAttachmentCurrent("STANDAL1"))
        assert.equals(1, env.http:callCount())
    end)

    it("counts the active file and remaining files when its worker is cancelled", function()
        local runner = Runner.new()
        runner.cancel_on = 1
        local result = api.downloadCollection("COLLAAA1", nil, function(task) return runner:run(task) end)
        assert.equals(2, result.cancelled)
        assert.equals(0, result.failed)
        assert.equals(0, env.http:callCount())
    end)

    it("does not confuse versions of sibling attachments", function()
        env:attachment("SIBLING", "PARENT01", "second.pdf", 1300)
        env:file("SIBLING", "sibling", 1300)
        env:file("ATTACH01", "stale", 1000)
        assert.is_false(api.isAttachmentCurrent("ATTACH01"))
        env.http:on("GET", "/items/ATTACH01/file", { body = "new" })
        assert.is_not_nil(api.downloadAndGetPath("ATTACH01"))
        assert.equals(1, env.http:callCount())
        assert.is_true(api.isAttachmentCurrent("SIBLING"))
    end)

    it("accepts a legacy marker only when one readable attachment uses its directory", function()
        env:file("ATTACH01")
        local directory = api.getDirAndPath("ATTACH01")
        api.util.write(directory .. "/version", "9999")
        assert.is_true(api.isAttachmentCurrent("ATTACH01"))
        env:attachment("SIBLING", "PARENT01", "second.pdf")
        assert.is_false(api.isAttachmentCurrent("ATTACH01"))
    end)

    it("preserves existing WebDAV files, versions and sidecars on an unpack failure", function()
        local path = env:file("ATTACH01", "old paper", 1)
        api.util.mkdir(path .. ".sdr")
        api.util.write(path .. ".sdr/metadata.lua", "progress")
        api.toggleWebDAVEnabled()
        api.setWebDAVUrl("https://example.org/zotero")
        env.http:on("GET", "/ATTACH01%.zip", { body = "invalid zip" })
        local downloaded, err = api.downloadAndGetPath("ATTACH01")
        assert.is_nil(downloaded)
        assert.is_not_nil(err)
        assert.equals("old paper", api.util.read(path))
        assert.equals("progress", api.util.read(path .. ".sdr/metadata.lua"))
        assert.equals("1", api.util.read(api.getVersionPath("ATTACH01")))
        assert.is_false(api.util.isFile(path .. ".part"))
    end)

    it("replaces stale staging files left by a cancelled process", function()
        local path = env:file("ATTACH01", "old paper", 1)
        api.util.write(path .. ".part", "interrupted")
        api.toggleWebDAVEnabled()
        api.setWebDAVUrl("https://example.org/zotero")
        env.http:on("GET", "/ATTACH01%.zip", { body = Fixtures.raw("attachment_misnamed.zip") })
        assert.equals(path, api.downloadAndGetPath("ATTACH01"))
        assert.equals("%PDF-1.4 pretend", api.util.read(path))
        assert.is_false(api.util.isFile(path .. ".part"))
    end)
end)
