require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Env = require("spec.support.zotero_env")
local Server = require("spec.support.fake_progress_server")
local Runtime = require("spec.support.fake_progress_runtime")
local Reader = require("spec.support.fake_progress_reader")
local Progress = require("zoteroprogress")
local Identity = require("zoteroprogressidentity")
local Remote = require("zoteroprogressremote")
local Codec = require("zoteroprogresscodec")
local FakeFileOpener = require("spec.support.fake_file_opener")
local FakeStoreDisk = require("spec.support.fake_store_disk")

describe("Zotero shared reading position", function()
    local env, api, server, runtime, progress, path, reader
    before_each(function()
        env = Env.new(); api = env.api; env:credentials(); env:library()
        path = env:file("ATTACH01", "PDF test contents")
        api.getItems().ATTACH01.data.md5 = Identity.checksum(path)
        server = Server.new(); api.http = server
        server.items.ATTACH01 = api.getItems().ATTACH01
        runtime = Runtime.new(); progress = Progress.new(api, runtime)
        reader = Reader.new(path, 4)
    end)
    after_each(function() Identity.open = io.open end)

    local function enable(existing)
        progress:toggle(); runtime:work()
        runtime.existing = existing
        progress:attach(reader, progress:prepare("ATTACH01", path))
    end
    local function synchronize()
        progress:sync(true); runtime:work()
        if #runtime.jobs > 0 then runtime:work() end
        assert.is_nil(server.last_error)
    end
    local function record() return progress.store:get(progress.session.identity) end
    -- Setup already hashed the attachment, so any later full read is a rehash.
    local function countReads()
        local opener = FakeFileOpener.new(); Identity.open = opener.open
        return opener
    end

    it("defaults off and makes no requests when opening or saving", function()
        progress:attach(reader, progress:prepare("ATTACH01", path)); progress:changed(); progress:sync()
        assert.is_false(progress:enabled()); assert.equals(0, #server.calls)
    end)
    it("checks permission before enabling and never enables Wi-Fi", function()
        runtime.online = false; progress:toggle(); assert.equals(0, #runtime.jobs)
        runtime.online = true; server.writable = false; progress:toggle(); runtime:work()
        assert.is_false(progress:enabled()); assert.truthy(progress.status:find("permission"))
    end)
    it("pushes preexisting local progress with zero-based physical pages", function()
        server:setting(15); enable(4); synchronize()
        assert.equals(3, server.settings.lastPageIndex_u_ATTACH01.value)
        assert.is_false(record().pending); assert.equals(4, reader.page)
    end)
    it("imports remote progress on the first open without old progress", function()
        reader.page = 1; server:setting(8); enable(nil); synchronize()
        assert.equals(9, reader.page); assert.equals(1, reader.saved)
        assert.equals(0, server.writes); assert.is_false(record().pending)
    end)
    it("does not turn initialization into local progress", function()
        reader.page = 1; server:setting(8); enable(nil)
        progress:checkpoint(); assert.is_false(record().pending)
    end)
    it("prefers local changes after both devices have moved", function()
        enable(4); synchronize()
        server:setting(15); reader.page = 7; progress:changed(); synchronize()
        assert.equals(6, server.settings.lastPageIndex_u_ATTACH01.value)
    end)
    it("refetches after one conflict and bounds repeated conflicts", function()
        enable(4); server.conflicts = 1; synchronize()
        assert.equals(1, server.writes); assert.is_false(record().pending)
        reader.page = 8; server.conflicts = 2; synchronize()
        assert.is_true(record().pending); assert.equals(0, server.conflicts)
    end)
    it("retries a conflict using the newest parent-process checkpoint", function()
        enable(4); server.conflicts = 1; progress:sync()
        reader.page = 9; progress:changed(); runtime:work(); runtime:work()
        assert.equals(8, server.settings.lastPageIndex_u_ATTACH01.value)
        assert.is_false(record().pending)
    end)
    it("shares, retries and pulls without rehashing an unchanged attachment", function()
        local opener = countReads()
        enable(4); synchronize()
        reader.page = 6; progress:changed(); server.conflicts = 1; synchronize()
        server:setting(9); synchronize()
        assert.equals(10, reader.page); assert.equals(0, opener:readCount(path))
    end)
    it("rehashes in full only once a replaced attachment invalidates its stamp", function()
        enable(4); local opener = countReads()
        assert.is_nil(api.util.write(path, "new contents")); progress:sync(); progress:sync()
        assert.equals(1, opener:readCount(path))
    end)
    it("retains a lost acknowledgment and retries without duplicate writes", function()
        enable(4); server.lose_write_response = true; synchronize()
        assert.is_true(record().pending); assert.equals(1, server.writes)
        server.lose_write_response = false; runtime.clock = runtime.clock + 61; synchronize()
        assert.equals(1, server.writes); assert.is_false(record().pending)
    end)
    it("rejects a remote pull after newer local navigation", function()
        reader.page = 1; server:setting(8); enable(nil); progress:sync()
        reader.page = 3; progress:changed(); runtime:work()
        assert.equals(3, reader.page); assert.is_true(record().pending)
    end)
    it("does not acknowledge a generation captured while a push is running", function()
        enable(4); progress:sync(); reader.page = 6; progress:changed(); runtime:work()
        assert.is_true(record().pending); assert.equals(5, record().value)
    end)
    it("queues offline checkpoints and survives coordinator restart", function()
        enable(4); runtime.online = false; reader.page = 8; progress:changed(); runtime:advance(2)
        local identity = progress.session.identity
        assert.is_true(progress.store:get(identity).pending)
        local next_progress = Progress.new(api, runtime)
        assert.equals(7, next_progress.store:get(identity).value)
        runtime.online = true; next_progress:sync(); runtime:work()
        assert.is_false(next_progress.store:get(identity).pending)
    end)
    it("flushes close and suspend without waiting for a worker", function()
        enable(4); reader.page = 10; progress:suspend()
        assert.equals(9, record().value)
        local identity = progress.session.identity
        reader.page = 11; progress:close(reader)
        assert.is_nil(progress.reader); assert.equals(10, progress.store:get(identity).value)
    end)
    it("disabling stops requests and retains progress", function()
        enable(4); reader.page = 7; local identity = progress.session.identity
        progress:toggle(); progress:sync()
        assert.is_false(progress:enabled()); assert.equals(6, progress.store:get(identity).value)
    end)
    it("does not accept responses after account switching", function()
        enable(4); local identity = progress.session.identity; progress:sync()
        assert.truthy(api.setAccount("group", "99", "different-key"))
        -- External settings edits can still invalidate a running snapshot.
        api.setAPIKey("different-key"); runtime:work()
        assert.is_true(progress.store:get(identity).pending)
    end)
    it("isolates group positions in the key owner's personal settings", function()
        assert.equals("https://api.zotero.org/users/4242/settings/lastPageIndex_g99_ATTACH01",
            Remote.settingURL({ owner = "4242", library = "groups/99", key = "ATTACH01" }))
        assert.has_error(function() Remote.settingURL({ owner = "4242", library = "users/99", key = "ATTACH01" }) end)
    end)
    it("rejects missing or changed attachment checksums", function()
        api.getItems().ATTACH01.data.md5 = nil; enable(4)
        assert.is_nil(progress.session); assert.truthy(progress.status:find("checksum"))
    end)
    it("checks live remote content before writing", function()
        enable(4); server.items.ATTACH01 = { data = { md5 = "different" } }; synchronize()
        assert.equals(0, server.writes); assert.is_true(record().pending)
    end)
    it("detects a local overwrite before sending", function()
        enable(4); assert.is_nil(api.util.write(path, "new contents")); progress:sync()
        assert.equals(0, #runtime.jobs); assert.equals(0, server.writes)
    end)
    it("honors server backoff and pauses on permission failure", function()
        enable(4); server.error_code = 429; synchronize()
        assert.equals(runtime.clock + 120, progress.next_try)
        progress:sync(); assert.equals(0, #runtime.jobs)
        runtime.clock = runtime.clock + 121; server.error_code = 403; synchronize()
        runtime.clock = runtime.clock + 121; progress:sync(); assert.equals(0, #runtime.jobs)
    end)
    it("stops the exchange on a successful response carrying Backoff", function()
        enable(4); server.item_headers = { backoff = "90" }; local before = #server.calls
        synchronize()
        assert.equals(before + 1, #server.calls)
        assert.equals(runtime.clock + 90, progress.next_try)
        assert.is_true(record().pending)
    end)
    it("does not reuse the acknowledgment of an attachment with replaced contents", function()
        enable(4); synchronize()
        api.util.write(path, "new verified PDF contents")
        api.getItems().ATTACH01.data.md5 = Identity.checksum(path, true)
        progress:attach(reader, progress:prepare("ATTACH01", path))
        assert.is_nil(progress.session); assert.truthy(progress.status:find("changed"))
    end)
    it("does not navigate to an invalid remote page", function()
        enable(4); synchronize(); server:setting(1000); synchronize()
        assert.equals(4, reader.page); assert.truthy(progress.status:find("Invalid"))
    end)
    it("validates PDF boundaries independently of displayed page labels", function()
        local codec = assert(Codec.new(reader, { format = "application/pdf" }))
        assert.equals(0, codec:encode(1)); assert.equals(19, codec:encode(20))
        assert.equals(1, codec:decode(0)); assert.equals(20, codec:decode(19))
        for _, invalid in ipairs({ -1, 20, 1.5, "iv" }) do assert.is_nil(codec:decode(invalid)) end
    end)
    it("creates a missing remote setting without losing initial enrollment", function()
        reader.page = 1; enable(nil); synchronize()
        assert.equals(0, server.settings.lastPageIndex_u_ATTACH01.value)
        assert.is_false(record().pending)
    end)
    it("retains within-page state when the shared PDF page is unchanged", function()
        server:setting(3); enable(nil); synchronize()
        assert.equals(0, reader.saved); assert.equals(4, reader.page)
    end)
    it("contains a corrupt outbox without blocking other Zotero operations", function()
        -- The parent owns the outbox and caches it after the first read, so corruption
        -- is found when a restarted coordinator loads the file.
        enable(4); api.util.write(progress.store.path, "invalid")
        local restarted = Progress.new(api, runtime)
        restarted:safe("sync", true)
        assert.is_nil(api.operation); assert.truthy(restarted.status:find("unavailable"))
    end)
    it("does not rewrite the outbox for checkpoints at the same position", function()
        enable(4); synchronize()
        local disk = FakeStoreDisk.new()
        progress.store.api = { zotero_dir = api.zotero_dir, util = disk }
        progress:checkpoint(); progress:checkpoint()
        assert.equals(0, disk.writes)
        reader.page = 6; progress:checkpoint()
        assert.equals(1, disk.writes)
    end)
    it("persists permission pauses across coordinator restart", function()
        enable(4); server.error_code = 403; synchronize()
        local replacement = Progress.new(api, runtime)
        runtime.clock = runtime.clock + 300; replacement:sync()
        assert.equals(0, #runtime.jobs)
        assert.truthy(replacement:statusText():find("403"))
    end)
    it("drains another closed attachment after the active document is shared", function()
        enable(4); local first = progress.session.identity
        progress:checkpoint(); progress:close(reader)
        env:attachment("SECOND01", "PARENT01", "second.pdf")
        local second_path = env:file("SECOND01", "second PDF")
        api.getItems().SECOND01.data.md5 = Identity.checksum(second_path)
        local opener = countReads()
        server.items.SECOND01 = api.getItems().SECOND01
        reader = Reader.new(second_path, 2)
        progress:attach(reader, progress:prepare("SECOND01", second_path))
        synchronize()
        for _ = 1, 3 do
            runtime:advance(1)
            while #runtime.jobs > 0 do runtime:work() end
        end
        assert.is_false(progress.store:get(first).pending)
        assert.equals(3, server.settings.lastPageIndex_u_ATTACH01.value)
        assert.equals(1, server.settings.lastPageIndex_u_SECOND01.value)
        assert.equals(second_path, progress.reader.document.file)
        assert.equals(0, opener:readCount(path)); assert.equals(0, opener:readCount(second_path))
    end)
    it("only schedules the latest change after idle and the cadence limit", function()
        enable(4); synchronize(); reader.page = 7; progress:changed()
        assert.equals(runtime.clock + 60, runtime.timers[progress.push_task])
        runtime:advance(2); assert.equals(6, record().value)
        reader.page = 8; progress:changed()
        assert.equals(2, (function() local n = 0; for _ in pairs(runtime.timers) do n = n + 1 end; return n end)())
    end)
end)
