require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Env = require("spec.support.zotero_env")
local Server = require("spec.support.fake_highlight_server")
local Reader = require("spec.support.fake_highlight_reader")
local Runtime = require("spec.support.fake_progress_runtime")
local Highlights = require("zoterohighlights")
local Identity = require("zoteroprogressidentity")
local Helpers = require("zoterohighlightutil")
local util = require("util")
local Codec = require("zoterohighlightcodec")
local Fixtures = require("spec.support.fixtures")
local FakeFileOpener = require("spec.support.fake_file_opener")

for _, kind in ipairs({ "pdf", "epub" }) do
    describe("Zotero bidirectional " .. kind .. " highlights", function()
        local env, api, reader, runtime, server, sync, path, native
        before_each(function()
            env = Env.new(); api = env.api; env:credentials(); env:library()
            local item = env:attachment("ATTACH01", "PARENT01", "sample." .. kind)
            item.data.contentType = kind == "pdf" and "application/pdf" or "application/epub+zip"
            path = env:file("ATTACH01", Fixtures.raw("positions/sample." .. kind))
            item.data.md5 = Identity.checksum(path, true); api.setItems(api.getItems())
            server = Server.new(); server.items.ATTACH01 = item; api.http = server
            runtime = Runtime.new(); reader = Reader.new(path, kind); native = reader:highlight(kind)
            sync = Highlights.new(api, runtime)
        end)
        after_each(function() reader:close(); Identity.open = io.open end)
        local function enable()
            sync:toggle(); runtime:work()
            sync:attach(reader, { key = "ATTACH01", path = path, library = "users/4242" })
        end
        local function record() return sync.store:get(sync.identity) end
        local function entry() return record().entries[native.zotero_highlight_id] end
        local function exchange()
            sync:sync(); if #runtime.jobs > 0 then runtime:work() end
            assert.is_nil(server.last_error)
        end
        local function remote() return assert(server.annotations[entry().key]) end
        local function edit(fields)
            local updated = util.tableDeepCopy(remote().data)
            for key, value in pairs(fields) do updated[key] = value end
            server:insert(entry().key, updated)
        end
        it("defaults off, including when reader events fire", function()
            sync:attach(reader, { key = "ATTACH01", path = path, library = "users/4242" }); sync:changed(); sync:sync()
            assert.is_false(sync:enabled()); assert.equals(0, #server.calls); assert.is_nil(native.zotero_highlight_id)
        end)
        it("checks write access independently of position sharing", function()
            server.writable = false; sync:toggle(); runtime:work(); assert.is_false(sync:enabled())
            assert.truthy(sync.status:find("permission")); server.writable = true; enable()
            assert.is_true(sync:enabled()); assert.is_nil(api.settings:readSetting("share_reading_position"))
        end)
        it("pushes, retries idempotently and preserves foreign annotations and reading settings", function()
            local bookmark = reader:bookmark(kind)
            reader.doc_settings:saveSetting("font_size", 29); reader.doc_settings:saveSetting("last_page", 3)
            enable(); exchange()
            assert.equals(1, server.writes, sync:statusText()); assert.equals("Alpha", remote().data.annotationText)
            exchange(); assert.equals(1, server.writes)
            assert.same(bookmark, reader.annotation.annotations[2])
            assert.equals(29, reader.doc_settings:readSetting("font_size")); assert.equals(3, reader.doc_settings:readSetting("last_page"))
        end)
        it("pulls edits while preserving remote tags, author metadata and position extras", function()
            enable(); exchange(); edit({ annotationComment = "Desktop note", tags = { { tag = "keep" } }, annotationAuthorName = "Author" })
            exchange(); native = reader.annotation.annotations[1]; assert.equals("Desktop note", native.note)
            native.note = "Reader note"; sync:changed(); exchange()
            assert.equals("Reader note", remote().data.annotationComment); assert.same({ { tag = "keep" } }, remote().data.tags)
            assert.equals("Author", remote().data.annotationAuthorName)
        end)
        it("keeps stable identities across edits and equal timestamps", function()
            local second = reader:highlight(kind); enable(); exchange()
            assert.is_not.equal(native.zotero_highlight_id, second.zotero_highlight_id)
            local key = entry().key; native.text = "Edited quotation"; sync:changed(); exchange()
            assert.equals(key, entry().key); assert.equals("Edited quotation", remote().data.annotationText)
        end)
        it("recovers a lost create acknowledgement without creating another item", function()
            enable(); server.lose_write_response = true; exchange(); assert.equals(1, server.writes)
            server.lose_write_response = false; runtime.clock = runtime.clock + 61; exchange()
            assert.equals(1, server.writes); assert.is_nil(entry().error)
        end)
        it("adopts an identical preexisting remote highlight", function()
            enable()
            local codec = Codec.open(sync.identity, record().dom_version)
            local fields = codec:fields(codec:encode(Helpers.native(native))); codec:close()
            fields.itemType, fields.parentItem = "annotation", "ATTACH01"
            server:insert("ABCDEFGH", fields); exchange()
            assert.equals("ABCDEFGH", entry().key); assert.equals(0, server.writes)
            assert.equals(1, #reader.annotation.annotations)
        end)
        it("merges disjoint edits and keeps overlapping edits unresolved", function()
            enable(); exchange(); native.note = "KOReader"; sync:changed(); edit({ annotationColor = "#ff6666" }); exchange()
            native = reader.annotation.annotations[1]; assert.equals("red", native.color); assert.equals("KOReader", native.note)
            native.note = "Local conflict"; sync:changed(); edit({ annotationComment = "Remote conflict" }); exchange()
            assert.truthy(entry().conflict); assert.equals("Local conflict", native.note)
            assert.equals("Remote conflict", remote().data.annotationComment)
            sync:resolve(native.zotero_highlight_id, "remote"); runtime:work()
            assert.equals("Remote conflict", reader.annotation.annotations[1].note); assert.is_nil(entry().conflict)
        end)
        it("propagates local deletion by trashing only the mapped remote highlight", function()
            enable(); exchange(); local key = entry().key
            reader.annotation.annotations = {}; sync:changed(); exchange()
            assert.equals(1, server.annotations[key].data.deleted); assert.is_false(entry().base)
            exchange(); assert.equals(2, server.writes)
        end)
        it("propagates remote deletion and does not resurrect tombstones", function()
            enable(); exchange(); edit({ deleted = 1 }); exchange()
            assert.equals(0, #reader.annotation.annotations); assert.is_false(entry().native)
            exchange(); assert.equals(1, server.writes)
        end)
        it("retains edit versus delete conflicts until explicitly resolved", function()
            enable(); exchange(); native.note = "Offline edit"; sync:changed(); edit({ deleted = 1 }); exchange()
            assert.truthy(entry().conflict); assert.equals("Offline edit", native.note)
            sync:resolve(native.zotero_highlight_id, "local"); runtime:work()
            assert.equals(0, remote().data.deleted); assert.equals("Offline edit", remote().data.annotationComment)
        end)
        it("rejects stale pulls after local editing during a request", function()
            enable(); exchange(); edit({ annotationComment = "Desktop" }); sync:sync()
            native.note = "New local"; sync:changed(); runtime:work()
            assert.equals("New local", native.note); exchange(); assert.truthy(entry().conflict)
        end)
        it("queues offline changes across coordinator restart", function()
            enable(); exchange(); runtime.online = false; native.note = "Offline"; sync:changed()
            sync = Highlights.new(api, runtime)
            sync:attach(reader, { key = "ATTACH01", path = path, library = "users/4242" })
            assert.equals("Offline", entry().native.note); runtime.online = true; exchange()
            assert.equals("Offline", remote().data.annotationComment)
        end)
        it("does not interpret failed pagination as deletion", function()
            enable(); exchange(); server.incomplete = true; exchange()
            assert.equals(1, #reader.annotation.annotations); assert.equals(1, server.writes)
            assert.truthy(sync.status:find("Incomplete"))
        end)
        it("retains unsupported local entries and skips unrelated remote types", function()
            enable(); exchange(); native.note_format = "html"; native.note = "<b>Keep</b>"; sync:changed()
            server:insert("ABCDEFGH", { itemType = "annotation", annotationType = "ink", parentItem = "ATTACH01" })
            exchange(); assert.equals("<b>Keep</b>", native.note); assert.truthy(entry().error); assert.equals(1, server.writes)
        end)
        it("stops on account changes and content replacement", function()
            enable(); exchange(); api.setAPIKey("different"); native.note = "private"; sync:changed(); exchange()
            assert.equals(1, server.writes)
        end)
        it("imports new remote highlights and refreshes the native highlight cache", function()
            enable(); exchange()
            local fields = util.tableDeepCopy(remote().data); fields.annotationText = "Different quoted text"; fields.annotationComment = "New desktop highlight"
            server:insert("ABCDEFGH", fields); exchange()
            assert.equals(2, #reader.annotation.annotations); assert.truthy(reader.refreshed)
            exchange(); assert.equals(2, #reader.annotation.annotations); assert.equals(1, server.writes)
        end)
        it("preserves a closed-document import journal across restart", function()
            enable(); exchange(); edit({ annotationComment = "While closed" })
            local identity = sync.identity
            sync:sync(); sync:close(reader); runtime:work()
            assert.truthy(sync.store:get(identity).delivery); assert.is_nil(native.note)
            sync = Highlights.new(api, runtime)
            sync:attach(reader, { key = "ATTACH01", path = path, library = "users/4242" })
            assert.is_nil(record().delivery); assert.equals("While closed", reader.annotation.annotations[1].note)
        end)
        it("does not overwrite an edit made while an import journal was waiting", function()
            enable(); exchange(); edit({ annotationComment = "Desktop waiting" })
            sync:sync(); sync:close(reader); runtime:work()
            native.note = "New offline edit"
            sync:attach(reader, { key = "ATTACH01", path = path, library = "users/4242" })
            assert.equals("New offline edit", native.note); exchange(); assert.truthy(entry().conflict)
        end)
        it("bounds 412 failures and reconciles again on the next trigger", function()
            enable(); exchange(); native.note = "New"; sync:changed(); server.conflicts = 1; exchange()
            assert.truthy(entry().error); assert.equals(1, server.writes)
            exchange(); assert.equals("New", remote().data.annotationComment)
        end)
        it("honors Backoff and persists permission pauses across restart", function()
            enable(); server.item_headers = { backoff = "90" }; local before = #server.calls; exchange()
            assert.equals(before + 1, #server.calls); assert.equals(runtime.clock + 90, sync.next_try)
            server.item_headers = nil; runtime.clock = runtime.clock + 91; server.error_code = 403; exchange()
            sync = Highlights.new(api, runtime); local requests = #server.calls; sync:sync()
            assert.equals(requests, #server.calls); assert.is_true(sync.paused)
        end)
        it("captures, exchanges and accepts without rehashing an unchanged attachment", function()
            -- Setup already hashed the attachment, so any later full read is a rehash.
            local opener = FakeFileOpener.new(); Identity.open = opener.open
            enable(); exchange(); native.note = "Edited"; sync:changed(); exchange()
            assert.equals("Edited", remote().data.annotationComment); assert.equals(0, opener:readCount(path))
        end)
        it("cancels background work and removes scratch files on suspend", function()
            enable(); sync:sync(); local job = runtime.jobs[1]
            sync:suspend(); assert.is_nil(api.operation); assert.is_true(job.done)
            assert.equals(0, server.writes)
        end)
        it("keeps a moved tracked annotation and its local counterpart intact", function()
            enable(); exchange(); edit({ parentItem = "OTHER001" }); exchange()
            assert.truthy(entry().error); assert.equals(1, #reader.annotation.annotations); assert.equals(1, server.writes)
        end)
        it("detects a replaced attachment before any network write", function()
            enable(); exchange(); api.util.write(path, "replacement")
            local before = #server.calls; sync:sync(); assert.equals(before, #server.calls)
            assert.truthy(sync.status:find("changed"))
        end)
        it("retains both versions when a conflict choice becomes stale", function()
            enable(); exchange(); native.note = "Local"; sync:changed(); edit({ annotationComment = "Remote" }); exchange()
            sync:resolve(native.zotero_highlight_id, "local")
            edit({ annotationComment = "New remote" }); runtime:work()
            assert.truthy(entry().conflict); assert.equals("New remote", remote().data.annotationComment)
        end)
        it("allows a reviewed local deletion to win an edit-versus-delete conflict", function()
            enable(); exchange(); reader.annotation.annotations = {}; sync:changed()
            edit({ annotationComment = "Remote edit" }); exchange(); assert.truthy(entry().conflict)
            sync:resolve(native.zotero_highlight_id, "local"); runtime:work()
            assert.equals(1, remote().data.deleted); assert.equals(0, #reader.annotation.annotations)
        end)
        it("does not import ambiguous duplicates over an existing local highlight", function()
            enable()
            local codec = Codec.open(sync.identity, record().dom_version)
            local fields = codec:fields(codec:encode(Helpers.native(native))); codec:close()
            fields.itemType, fields.parentItem = "annotation", "ATTACH01"
            server:insert("ABCDEFGH", fields); server:insert("BCDEFGHJ", fields); exchange()
            assert.equals(0, server.writes); assert.equals(1, #reader.annotation.annotations); assert.truthy(entry().error)
        end)
        it("preserves remote position extensions when only a note is edited", function()
            enable(); exchange()
            local fields = util.tableDeepCopy(remote().data)
            local position = require("json").decode(fields.annotationPosition); position.fixtureExtension = "keep"
            fields.annotationPosition = require("json").encode(position); server:insert(entry().key, fields)
            native.note = "New note"; sync:changed(); exchange()
            assert.equals("keep", require("json").decode(remote().data.annotationPosition).fixtureExtension)
        end)
        it("defers identical desktop-only copies until their ambiguity is resolved", function()
            enable()
            local codec = Codec.open(sync.identity, record().dom_version)
            local fields = codec:fields(codec:encode(Helpers.native(native))); codec:close()
            fields.itemType, fields.parentItem = "annotation", "ATTACH01"
            reader.annotation.annotations = {}; sync:changed()
            server:insert("ABCDEFGH", fields); server:insert("BCDEFGHJ", fields); exchange()
            assert.equals(0, #reader.annotation.annotations); assert.equals(0, server.writes)
            assert.equals(2, #record().warnings); assert.truthy(sync:statusText():find("Duplicate"))
            fields.deleted = 1; server:insert("BCDEFGHJ", fields); exchange()
            assert.equals(1, #reader.annotation.annotations); assert.equals(0, server.writes)
        end)
        it("does not import a new desktop duplicate of an already mapped highlight", function()
            enable(); exchange(); server:insert("ABCDEFGH", util.tableDeepCopy(remote().data)); exchange()
            assert.equals(1, #reader.annotation.annotations); assert.equals(1, server.writes)
            assert.equals(1, #record().warnings); assert.truthy(server.annotations.ABCDEFGH)
        end)
        it("checks actual group permission rather than personal write access", function()
            local Remote = require("zoterohighlightremote")
            assert.has_error(function() Remote.authorize(api, api.getAPIKey(), "groups/99") end)
            server.group_writable = true; assert.equals("groups/99", Remote.authorize(api, api.getAPIKey(), "groups/99").library)
        end)
    end)
end
