require("commonrequire")
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
local Env = require("spec.support.zotero_env")
local FakeUI = require("spec.support.fake_ui")
local FakeReader = require("spec.support.fake_reader")
local Browser = require("zoterobrowser")
local ReaderReturn = require("zoteroreader")
local UI = require("zoteroui")
local Plugin = dofile("plugins/zotero.koplugin/main.lua")
local PluginLoader = require("pluginloader")

describe("Zotero everyday navigation", function()
    local env, api, runtime, browser, plugin, loaded_plugins
    before_each(function()
        env = Env.new()
        api = env.api
        env:credentials()
        env:library()
        runtime = FakeUI.new()
        browser = Browser:new{ api = api, runtime = runtime, width = 600, height = 800,
            items_per_page = 2, is_enable_shortcut = false, close_callback = function() end }
        plugin = setmetatable({ api = api, runtime = runtime, browser = browser,
            initialized = true, zotero_dialog = {} }, { __index = Plugin })
        loaded_plugins = PluginLoader.loaded_plugins
        PluginLoader.loaded_plugins = { zotero = plugin }
        browser:restoreLibrary()
    end)
    after_each(function()
        browser:free()
        PluginLoader.loaded_plugins = loaded_plugins
    end)

    it("opens home with all five destinations through the existing gesture event", function()
        plugin:onZoteroOpenAction()
        assert.equals("home", browser.current_view.kind)
        assert.same({ "Continue reading", "Collections", "All items", "On device", "Search" }, Env.texts(browser.item_table))
        assert.is_false(browser.item_table[1].enabled)
        browser:onMenuSelect(browser.item_table[1])
        assert.is_nil(runtime.opened_path)
        assert.equals(plugin.zotero_dialog, runtime:last())
        assert.equals(0, env.http:callCount())
    end)

    it("keeps Home and Back visible and restores the source page through native controls", function()
        browser:onGotoPage(2)
        browser:onMenuSelect(browser.item_table[3])
        assert.equals("all", browser.current_view.kind)
        browser:onGotoPage(2)
        local header = browser.title_bar
        assert.equals("Home", header.controls.buttons_layout[1][1].text)
        assert.equals("Back", header.controls.buttons_layout[1][2].text)
        assert.is_true(header:getHeight() > header.caption:getHeight())
        assert.equals(4, #header:generateVerticalLayout())
        header.controls.buttons_layout[1][1].callback()
        assert.equals("Zotero home", header.caption.title_widget.text)
        local depth = #browser.paths
        browser:onHome()
        assert.equals(depth, #browser.paths)
        header.controls.buttons_layout[1][2].callback()
        assert.equals("all", browser.current_view.kind)
        assert.equals(2, browser.page)
        browser:onReturn()
        assert.equals("home", browser.current_view.kind)
        assert.equals(2, browser.page)
        browser:onReturn()
        assert.equals("home", browser.current_view.kind)
    end)

    it("names collections and search queries and restores nested collection pages", function()
        browser:onMenuSelect(browser.item_table[2])
        assert.equals("Zotero - Collections", browser:locationTitle())
        assert.equals(2, #browser.item_table)
        browser:navigate{ kind = "collection", key = "COLLAAA1" }
        browser:onGotoPage(2)
        assert.equals("Zotero - Papers", browser:locationTitle())
        browser:navigate{ kind = "collection", key = "COLLCCC3" }
        assert.equals("Zotero - Subfolder", browser:locationTitle())
        browser:navigate{ kind = "search", query = "attention [2017]" }
        assert.equals("Zotero - Search: attention [2017]", browser.title_bar.caption.title_widget.text)
        browser:onReturn()
        browser:onReturn()
        assert.equals("COLLAAA1", browser.current_view.key)
        assert.equals(2, browser.page)
    end)

    it("opens Search from home and keeps device queries local with an explicit title", function()
        browser:onMenuSelect(browser.item_table[5])
        runtime:last().buttons[1][1].callback()
        assert.equals(0, #browser.paths)
        browser.title_bar.controls.buttons_layout[1][3].callback()
        runtime:last().input = "attention"
        runtime:last().buttons[1][2].callback()
        assert.equals("search", browser.current_view.kind)
        browser:onHome()
        browser:onMenuSelect(browser.item_table[4])
        browser:onLeftButtonTap()
        runtime:last().input = "attention"
        runtime:last().buttons[1][2].callback()
        assert.equals("Zotero - On device: attention", browser:locationTitle())
        assert.is_true(browser.item_table[1].is_label)
        assert.equals(0, env.http:callCount())
    end)

    it("persists home and all-items history while accepting legacy collection snapshots", function()
        browser:navigate{ kind = "all" }
        browser:onGotoPage(2)
        browser:onHome()
        api.init(env.root)
        browser:restoreLibrary()
        assert.equals("home", browser.current_view.kind)
        browser:onReturn()
        assert.equals("all", browser.current_view.kind)
        assert.equals(2, browser.page)
        api.saveBrowserPosition("users/4242", { view = { kind = "collection", key = "COLLAAA1", page = 2 } })
        browser:restoreLibrary()
        assert.equals("COLLAAA1", browser.current_view.key)
        assert.equals(2, browser.page)
    end)

    it("remembers home pages even before the selected library has a cache", function()
        api.setAccount("group", "99", "key")
        browser:restoreLibrary()
        browser:onGotoPage(2)
        browser:onMenuSelect(browser.item_table[3])
        browser:onReturn()
        assert.equals("home", browser.current_view.kind)
        assert.equals(2, browser.page)
    end)

    it("continues the last successful plugin document at its exact path offline", function()
        local path = env:file("ATTACH01")
        browser:navigate{ kind = "collection", key = "COLLAAA1" }
        browser:onGotoPage(2)
        browser:onMenuSelect(browser.item_table[3])
        assert.equals(path, runtime.opened_path)
        assert.equals(2, runtime.reader_return.position.view.page)
        assert.equals("COLLAAA1", runtime.reader_return.position.view.key)
        api.getSettings():delSetting("api_key")
        api.saveModifiedItems()
        api.init(env.root)
        browser:onHome()
        assert.is_true(browser.item_table[1].enabled)
        assert.equals("Attention Is All You Need", browser.item_table[1].subtitle)
        browser:onMenuSelect(browser.item_table[1])
        assert.equals(path, runtime.opened_path)
        assert.equals("home", runtime.reader_return.position.view.kind)
        assert.equals(0, env.http:callCount())
    end)

    it("keeps Continue reading fully visible above long titles on narrow screens", function()
        local path = env:file("ATTACH01")
        api.getItems().PARENT01.data.title = string.rep("A long document title ", 30)
        api.saveContinueReading("users/4242", "ATTACH01", path)
        browser.items_font_size = 28
        browser:displayHome()
        browser:paintTo(require("device").screen.bb, 0, 0)
        local row = browser.item_group[1]
        local fields = row.navigation_widgets
        assert.equals(require("ui/bidi").auto("Continue reading"), fields.title.text)
        assert.is_nil(fields.title.line_with_ellipsis)
        assert.is_true(fields.subtitle:isTruncated())
        assert.is_true(fields.title.overlap_offset[2] + fields.title:getSize().h <= fields.subtitle.overlap_offset[2])
        assert.is_true(fields.subtitle.overlap_offset[2] + fields.subtitle:getSize().h <= row.dimen.h)
    end)

    it("does not remember failed opens or download cancellations", function()
        runtime.runner.cancel_on = 1
        browser:onMenuSelect({ key = "ATTACH01" })
        assert.is_nil(api.getContinueReading("users/4242"))
        env:file("ATTACH01")
        runtime.openReader = function(self, path, after_open) self.pending_open = after_open end
        browser:onMenuSelect({ key = "ATTACH01" })
        assert.is_nil(api.getContinueReading("users/4242"))
        assert.is_function(runtime.pending_open)
    end)

    it("isolates recent documents by library and rechecks removal and path changes", function()
        local path = env:file("ATTACH01")
        api.saveContinueReading("users/4242", "ATTACH01", path)
        api.setAccount("group", "4242", "key")
        env:library()
        local group_path = env:file("ATTACH01")
        assert.is_nil(api.getContinueReading("users/4242"))
        assert.is_nil(api.getContinueReading("groups/4242"))
        api.saveContinueReading("groups/4242", "ATTACH01", group_path)
        assert.equals(group_path, api.getContinueReading("groups/4242").path)
        api.setAccount("user", "4242", "key")
        env:library()
        assert.equals(path, api.getContinueReading("users/4242").path)
        browser:restoreLibrary()
        browser:displayHome()
        assert(os.remove(path))
        browser:onMenuSelect(browser.item_table[1])
        assert.is_false(browser.item_table[1].enabled)
        assert.is_nil(runtime.opened_path)
        env:file("ATTACH01")
        api.saveContinueReading("users/4242", "ATTACH01", group_path)
        assert.is_nil(api.getContinueReading("users/4242"))
        api.getSettings():saveSetting("continue_reading", { ["users/4242"] = { key = false } })
        assert.is_nil(api.getContinueReading("users/4242"))
    end)

    it("returns through the mounted plugin after native close without automatic sync", function()
        browser:navigate{ kind = "collection", key = "COLLAAA1" }
        browser:onGotoPage(2)
        local position = api.getBrowserPosition("users/4242")
        local reader = FakeReader.new("/tmp/paper.pdf")
        UI.bindReaderReturn(runtime, reader, "users/4242", position)
        browser:navigate{ kind = "search", query = "later gesture" }
        reader:onHome()
        assert.same({ "saved and closed", "file manager" }, reader.events)
        assert.equals(plugin.zotero_dialog, runtime:last())
        assert.equals("COLLAAA1", browser.current_view.key)
        assert.equals(2, browser.page)
        assert.equals(0, #runtime.scheduled)
        browser:onReturn()
        assert.equals("home", browser.current_view.kind)
    end)

    it("does not leak the return destination into an account selected while reading", function()
        browser:navigate{ kind = "all" }
        browser:onGotoPage(2)
        local reader = FakeReader.new("/tmp/paper.pdf")
        UI.bindReaderReturn(runtime, reader, "users/4242", api.getBrowserPosition("users/4242"))
        api.setAccount("group", "99", "key")
        env:library()
        browser:restoreLibrary()
        browser:navigate{ kind = "device" }
        reader:onHome()
        assert.equals("device", browser.current_view.kind)
        assert.equals("groups/99", browser.position_library)
        assert.equals(2, api.getBrowserPosition("users/4242").view.page)
    end)

    it("leaves ordinary readers and plain close, quit or switch teardown alone", function()
        local ordinary = FakeReader.new("/tmp/ordinary.pdf")
        local zotero = FakeReader.new("/tmp/zotero.pdf")
        local returns = 0
        ReaderReturn.bind(zotero, function() returns = returns + 1 end)
        ordinary:onHome()
        zotero:onClose()
        assert.equals(0, returns)
        zotero:showFileManager("/tmp/zotero.pdf", { selected = true })
        zotero:showFileManager("/tmp/zotero.pdf")
        assert.equals(1, returns)
        assert.equals(FakeReader.showFileManager, ordinary.showFileManager)
    end)

    it("retains return behavior across reloads and calls existing reload callbacks", function()
        local reader = FakeReader.new("/tmp/paper.epub")
        local returned, closed, opened = 0, false, false
        ReaderReturn.bind(reader, function() returned = returned + 1 end)
        reader:reloadDocument(function(path) closed = path end, true,
            function(reopened) opened = reopened.document.file end)
        assert.equals("/tmp/paper.epub", closed)
        assert.equals(closed, opened)
        assert.is_true(reader.seamless)
        assert.equals(0, returned)
        reader.reopened:onHome()
        assert.equals(1, returned)
    end)
end)
