-- Run from the emulator directory with a fresh KO_HOME under /tmp.
-- HTTP uses fixtures. Screenshots and settings stay under KO_HOME.
require("setupkoenv")
local root = require("datastorage"):getDataDir()
assert(root:match("^/tmp/") or root:match("^/private/tmp/"), "Use a temporary KO_HOME")
G_defaults = require("luadefaults"):open(root .. "/defaults.lua")
G_reader_settings = require("luasettings"):open(root .. "/settings.reader.lua")
local Device = require("device")
require("document/canvascontext"):init(Device)
require("ui/bidi").setup()
package.path = "plugins/zotero.koplugin/?.lua;" .. package.path
package.reload = function(name) package.loaded[name] = nil return require(name) end
local UIManager = require("ui/uimanager")
local env = require("spec.support.zotero_env").new()
local Plugin = dofile("plugins/zotero.koplugin/main.lua")
local plugin = Plugin:new{ api = env.api, ui = { menu = { registerToMainMenu = function() end } } }
assert(plugin.initialized)
local api, browser = plugin.api, plugin.browser
assert(api.util.mkdir(root .. "/screenshots"))
env:credentials()
env:library()
local original = env:file("ATTACH01", "old paper", 1)
api.util.mkdir(original .. ".sdr")
api.util.write(original .. ".sdr/metadata.lua", "progress")
env.http:on("GET", "/items/STANDAL1/file", { body = "standalone" })
env.http:on("GET", "/items/ATTACH01/file", { body = "updated paper" })
local fake_request = env.http.request
env.http.request = function(request)
    require("ffi/util").usleep(350000)
    return fake_request(request)
end

local function top()
    return UIManager._window_stack[#UIManager._window_stack].widget
end

local function closeTop()
    UIManager:close(top())
end

local function shot(name)
    UIManager:forceRePaint()
    Device.screen:shot(root .. "/screenshots/" .. name .. ".png")
    print("SMOKE " .. name)
end

local steps = {}
local function step(name, action)
    table.insert(steps, { name = name, action = action })
end

step("00-home", function()
    assert(browser.current_view.kind == "home")
    assert(#browser.item_table == 5)
    assert(browser.title_bar.controls.buttons_layout[1][1].text == "Home")
    assert(browser.title_bar.controls.buttons_layout[1][2].text == "Back")
end)
step("01-browser", function()
    browser:displayCollection("COLLAAA1")
end)
step("02-library-selector", function() plugin:setAccount() end)
step("03-group-account", function()
    local selector = top()
    selector.provider = "group"
    selector.callback(selector)
    UIManager:close(selector)
    assert(top().input_fields[1]:getText() == "")
end)
step("04-group-library", function()
    local dialog = top()
    dialog.input_fields[1]:setText("99")
    dialog.buttons[1][2].callback()
    assert(api.getLibraryPrefix() == "groups/99")
    env:library()
    browser:displayCollection("COLLAAA1")
    assert(not api.displaySearchResults("attention")[1].downloaded)
end)
step("05-notes-menu", function() browser:onMenuHold({ key = "ATTACH01", text = "Attention Is All You Need" }) end)
step("06-notes", function() top().buttons[1][1].callback() end)
step("07-tag-dialog", function()
    closeTop()
    assert(not api.setAccount("user", "4242", "offline-test-key"))
    browser:restoreLibrary()
    env:library()
    api.getItems().PARENT01.data.tags = { { tag = "Read" } }
    api.setItems(api.getItems())
    browser:displayCollection("COLLAAA1")
    plugin:setFilterTag()
end)
step("08-filtered", function()
    local dialog = top()
    dialog:setInputText("Read")
    dialog.buttons[1][3].callback()
    assert(#api.displaySearchResults("") == 1)
end)
step("09-download-menu", function()
    plugin:setFilterTag()
    top().buttons[1][2].callback()
    browser:onMenuHold({ key = "COLLAAA1", text = "Papers/", collection = true })
end)
step("10-progress", function() top().buttons[1][1].callback() end)
step("11-complete", function()
    assert(not api.operation, "download should be finished")
    assert(api.isAttachmentCurrent("ATTACH01"))
    assert(api.isAttachmentCurrent("STANDAL1"))
    assert(api.util.read(original .. ".sdr/metadata.lua") == "progress")
    assert(top().text:find("Downloaded: 2", 1, true))
end)
step("12-cancel-progress", function()
    closeTop()
    api.getItems().ATTACH01.version = 9999
    api.getItems().STANDAL1.version = 9999
    browser:startDownload(function() browser:downloadCollection("COLLAAA1") end)
end)
step("13-cancelled", function()
    assert(browser.download_dialog, "active progress dialog expected")
    browser.download_dialog:onTapClose()
    assert(not api.operation)
    assert(top().text:find("Cancelled: 2", 1, true))
    assert(api.util.read(original) == "updated paper")
end)
step("14-offline-browser", function()
    closeTop()
    browser:displayCollection("COLLAAA1")
    assert(api.displaySearchResults("attention")[1].downloaded)
end)

step("15-metadata-collection", function()
    local items = api.getItems()
    items.LINKED01.data.collections = { "COLLAAA1" }
    items.LONGP = { key = "LONGP", version = 1, meta = { creatorSummary = "Chen et al.", parsedDate = "2024-01-01" },
        data = { itemType = "journalArticle", collections = { "COLLAAA1" },
            title = "Understanding long publication titles on electronic paper displays: metadata, readability, and accessible navigation across very large research libraries" } }
    api.setItems(items)
    env:attachment("LONGFILE", "LONGP", "long-title.pdf")
    env:attachment("ORPHAN", "MISSING", "orphan-report.pdf")
    items = api.getItems()
    items.ORPHAN.data.title = ""
    items.PARENT02.data.collections = { "COLLAAA1", "COLLCCC3" }
    items.PARENT02.meta.creatorSummary = nil
    items.PARENT02.meta.parsedDate = "2008"
    api.setItems(items)
    browser.is_enable_shortcut = false
    browser:displayCollection("COLLAAA1")
    assert(browser.item_group[1].entry.collection)
    assert(browser.item_group[2].metadata_widgets.status.text == "Unavailable")
    assert(browser.item_group[3].metadata_widgets.status.text == "Downloaded")
end)
step("16-metadata-search", function()
    browser:displaySearchResults("")
    assert(api.displaySearchResults("orphan-report.pdf")[1].title == "orphan-report.pdf")
    local long_title = browser.item_group[3].metadata_widgets.title
    assert(long_title.line_with_ellipsis == 2)
    assert(browser.item_group:getSize().h <= browser.available_height)
end)
step("17-metadata-large-font", function()
    browser.items_font_size = 36
    browser:displayCollection("COLLAAA1")
    assert(browser.page_num > 1)
    assert(browser.item_group:getSize().h <= browser.available_height)
end)
step("18-metadata-large-search", function()
    browser:displaySearchResults("")
    assert(browser.page_num > 1)
    assert(browser.item_group:getSize().h <= browser.available_height)
end)
step("19-metadata-next-page", function()
    browser:onNextPage()
    assert(browser.page == 2)
    assert(browser.item_group[1].idx == browser.perpage + 1)
end)
step("20-metadata-collections", function()
    browser.items_font_size = nil
    browser:displayCollection(nil)
    assert(browser.item_group[1].entry.collection)
    assert(browser.item_group[2].entry.collection)
end)

local DocSettings = require("docsettings")
local ReaderUI = require("apps/reader/readerui")
local local_pdf, local_epub, pdf_contents, epub_contents, offline_http, epub_xpointer
step("21-on-device", function()
    pdf_contents = assert(api.util.read("../../test/2col.pdf"))
    epub_contents = assert(api.util.read("../../test/leaves.epub"))
    local_pdf = env:file("ATTACH01", pdf_contents, 1)
    local_epub = env:file("ATTACH02", epub_contents)
    local settings = DocSettings:open(local_pdf)
    settings:saveSetting("zotero_smoke_marker", "preserved sidecar")
    settings:saveSetting("last_page", 2)
    settings:flush()
    api.getSettings():delSetting("api_key")
    api.getSettings():delSetting("user_id")
    api.saveModifiedItems()
    api.init(root .. "/zotero")
    offline_http = require("spec.support.fake_http").new()
    api.http = offline_http
    assert(not api.getLibraryPrefix())
    assert(api.getLocalLibraryPrefix() == "users/4242")
    browser.items_per_page = 2
    api.getSettings():saveSetting("items_per_page", 2)
    api.saveModifiedItems()
    browser:displayHome()
    browser:onMenuSelect(browser.item_table[4])
    assert(browser.current_view.kind == "device")
    assert(#browser.item_table == 3)
end)
step("22-on-device-page", function()
    browser:onNextPage()
    assert(browser.page == 2)
    assert(browser.item_group[1].entry.key == "ATTACH01")
end)
step("23-offline-pdf", function()
    browser:onMenuSelect(browser.item_group[1].entry)
end)
step("24-pdf-sidecar", function()
    local reader = assert(ReaderUI.instance, "local PDF reader expected")
    assert(reader.document.file == local_pdf)
    assert(reader.doc_settings:readSetting("zotero_smoke_marker") == "preserved sidecar")
    assert(reader.view.state.page == 2)
    assert(api.util.read(local_pdf) == pdf_contents)
    assert(api.util.read(api.getVersionPath("ATTACH01")) == "1")
    assert(offline_http:callCount() == 0)
end)
step("25-return-to-device-page", function()
    ReaderUI.instance.paging:onGotoPage(1)
    ReaderUI.instance:onHome()
    plugin = assert(require("pluginloader"):getPluginInstance("zotero"))
    browser = plugin.browser
    assert(top() == plugin.zotero_dialog)
    assert(not ReaderUI.instance)
    assert(DocSettings:open(local_pdf):readSetting("last_page") == 1)
    assert(browser.current_view.kind == "device")
    assert(browser.page == 2)
    assert(DocSettings:open(local_pdf):readSetting("zotero_smoke_marker") == "preserved sidecar")
end)
step("26-offline-epub", function()
    for row, entry in ipairs(browser.item_table) do
        if entry.key == "ATTACH02" then
            browser:onGotoPage(browser:getPageNumber(row))
            browser:onMenuSelect(entry)
            return
        end
    end
    error("Expected local EPUB ATTACH02 in On device")
end)
step("27-epub-opened", function()
    assert(ReaderUI.instance.document.file == local_epub)
    assert(api.util.read(local_epub) == epub_contents)
    assert(offline_http:callCount() == 0)
    ReaderUI.instance.rolling:onGotoPage(3)
    epub_xpointer = ReaderUI.instance.rolling.xpointer
end)
step("28-library-position", function()
    ReaderUI.instance.menu:getDefaultMenuButtons().filemanager.callback()
    plugin = assert(require("pluginloader"):getPluginInstance("zotero"))
    browser = plugin.browser
    assert(top() == plugin.zotero_dialog)
    assert(browser.current_view.kind == "device")
    assert(browser.page == 1)
    assert(DocSettings:open(local_epub):readSetting("last_xpointer") == epub_xpointer)
    browser:navigate{ kind = "device", query = "attention" }
    browser:savePosition()
    assert(not api.setAccount("group", "99", ""))
    browser:restoreLibrary()
    browser:navigate{ kind = "search", query = "group query" }
    assert(not api.setAccount("user", "4242", ""))
    browser:restoreLibrary()
    env:library()
    browser:refresh()
    assert(browser.current_view.kind == "device")
    assert(browser.current_view.query == "attention")
    assert(#browser.item_table == 1 and browser.item_table[1].downloaded)
    assert(offline_http:callCount() == 0)
end)

step("29-collection-page", function()
    browser:navigate{ kind = "collection", key = "COLLAAA1" }
    browser:onGotoPage(2)
    assert(browser:locationTitle() == "Zotero - Papers")
end)
step("30-collection-document", function()
    browser:onMenuSelect(browser.item_table[3])
end)
step("31-gesture-in-reader", function()
    assert(ReaderUI.instance.document.file == local_pdf)
    assert(ReaderUI.instance.view.state.page == 1)
    ReaderUI.instance:handleEvent(require("ui/event"):new("ZoteroOpenAction"))
    local reader_plugin = require("pluginloader"):getPluginInstance("zotero")
    assert(top() == reader_plugin.zotero_dialog)
    assert(reader_plugin.browser.current_view.key == "COLLAAA1")
    assert(reader_plugin.browser.page == 2)
    reader_plugin.browser:onHome()
    assert(reader_plugin.browser.current_view.kind == "home")
    reader_plugin.browser.title_bar.controls.buttons_layout[1][2].callback()
    assert(reader_plugin.browser.current_view.key == "COLLAAA1")
    assert(reader_plugin.browser.page == 2)
    reader_plugin.browser:onCloseAllMenus()
end)
step("31a-reload-document", function()
    ReaderUI.instance:reloadDocument()
end)
step("31b-reloaded-document", function()
    assert(ReaderUI.instance.document.file == local_pdf)
    assert(ReaderUI.instance.view.state.page == 1)
end)
step("32-return-to-collection", function()
    ReaderUI.instance:onHome()
    plugin = assert(require("pluginloader"):getPluginInstance("zotero"))
    browser = plugin.browser
    assert(top() == plugin.zotero_dialog)
    assert(browser.current_view.key == "COLLAAA1")
    assert(browser.page == 2)
end)
step("33-continue-reading-home", function()
    browser.title_bar.controls.buttons_layout[1][1].callback()
    assert(browser.current_view.kind == "home")
    assert(browser.item_table[1].enabled)
end)
step("34-continue-reading-document", function()
    browser:onMenuSelect(browser.item_table[1])
end)
step("35-continue-reading-return", function()
    assert(ReaderUI.instance.document.file == local_pdf)
    assert(ReaderUI.instance.view.state.page == 1)
    ReaderUI.instance:onHome()
    plugin = assert(require("pluginloader"):getPluginInstance("zotero"))
    browser = plugin.browser
    assert(top() == plugin.zotero_dialog)
    assert(browser.current_view.kind == "home")
end)
step("36-ordinary-document", function()
    browser:onCloseAllMenus()
    ReaderUI:showReader(local_pdf)
end)
step("37-ordinary-document-return", function()
    assert(ReaderUI.instance.document.file == local_pdf)
    ReaderUI.instance:onHome()
    assert(top() == require("apps/filemanager/filemanager").instance)
    assert(api.util.read(local_pdf) == pdf_contents)
    assert(api.util.read(local_epub) == epub_contents)
    assert(DocSettings:open(local_pdf):readSetting("zotero_smoke_marker") == "preserved sidecar")
    assert(offline_http:callCount() == 0)
end)

-- Library sync runs in a real forked worker. Only its small result crosses the pipe.
local lfs = require("libs/libkoreader-lfs")
local items_inode
local function stageClear()
    for _, path in pairs(api.getSyncStage()) do
        if lfs.attributes(path) or lfs.attributes(path .. ".tmp") then return false end
    end
    return true
end
step("38-sync-progress", function()
    plugin = assert(require("pluginloader"):getPluginInstance("zotero"))
    browser = plugin.browser
    env:credentials()
    api.http = env.http
    env:syncRoutes()
    items_inode = lfs.attributes(api.getCachePath("items"), "ino")
    plugin:onZoteroOpenAction()
    plugin:onZoteroSyncAction()
    assert(api.operation == "sync")
    assert(top().text:find("tap to cancel", 1, true))
end)
step("39-sync-cancelled", function()
    top():onTapClose()
    assert(not api.operation)
    assert(api.getLastSync() == 0)
    assert(lfs.attributes(api.getCachePath("items"), "ino") == items_inode)
    assert(stageClear())
    assert(top().text:find("cancelled", 1, true))
end)
step("40-sync-running", function()
    closeTop()
    plugin:onZoteroSyncAction()
end)
step("41-sync-committed", function()
    assert(not api.operation, "sync should be finished")
    assert(api.getLastSync() > 0)
    assert(api.getLibraryVersion() == "1230")
    assert(lfs.attributes(api.getCachePath("items"), "ino") ~= items_inode)
    assert(stageClear())
    assert(top().text == "Success.")
end)
step("42-auto-sync-browsing", function()
    closeTop()
    api.setSyncOnOpen(true)
    api.setLastSync(1)
    plugin:maybeAutoSync("open")
    assert(api.operation == "sync")
    assert(top() == plugin.zotero_dialog)
    browser:displayCollection("COLLAAA1")
end)
step("43-auto-sync-committed", function()
    assert(not api.operation, "automatic sync should be finished")
    assert(api.getLastSync() > 1)
    assert(stageClear())
    assert(top() == plugin.zotero_dialog)
end)

local index, finished = 0, false
local function advance()
    index = index + 1
    local current = steps[index]
    if not current then finished = true print("SMOKE PASS: " .. #steps .. " screens") UIManager:quit() return end
    local ok, err = xpcall(function() current.action() shot(current.name) end, debug.traceback)
    if not ok then print("SMOKE FAIL: " .. tostring(err)) UIManager:quit(1) return end
    -- Allow the first reader's temporary database notification to leave the screenshots.
    local delay = current.name == "23-offline-pdf" and 3.5 or current.name == "10-progress" and 1.5
        or (current.name == "40-sync-running" or current.name == "42-auto-sync-browsing") and 3
        or (current.name == "12-cancel-progress" or current.name == "38-sync-progress") and 0.05 or 0.35
    UIManager:scheduleIn(delay, advance)
end

plugin:onZoteroOpenAction()
UIManager:scheduleIn(0.1, advance)
UIManager:scheduleIn(60, function() print("SMOKE TIMEOUT") UIManager:quit(1) end)
local result = UIManager:run()
Device:exit()
os.exit(finished and (result or 0) or 1)
